### ISSUE TITLE
Error loading tracks; Discrepancy between column "genre/s_top" in util.py, tracks.csv and usage.ipynb

### ISSUE THREAD

**Issue by victoreram** [mdeff/fma#21] opened 2018-02-20 21:55 UTC
In line 201 in utils.py, one of the columns being called is
` ('track', 'genres_top')`
but shouldn't it be
`('track', 'genre_top')`
based on tracks.csv? 

However when I make that change, I get the following error:
```python
ValueError                                Traceback (most recent call last)
<ipython-input-5-eecca7133c46> in <module>()
----> 1 tracks = utils.load('fma_metadata/tracks.csv')
      2 genres = utils.load('fma_metadata/genres.csv')
      3 features = utils.load('fma_metadata/features.csv')
      4 echonest = utils.load('fma_metadata/echonest.csv')
      5 

~\OneDrive\Documents\GitHub\fma\utils.py in load(filepath)
    201                    ('track', 'genre_top')]
    202         for column in COLUMNS:
--> 203             tracks[column] = tracks[column].map(ast.literal_eval)
    204 
    205         COLUMNS = [('track', 'date_created'), ('track', 'date_recorded'),

C:\Anaconda3\lib\site-packages\pandas\core\series.py in map(self, arg, na_action)
   2052                                      index=self.index).__finalize__(self)
   2053         else:
-> 2054             mapped = map_f(values, arg)
   2055             return self._constructor(mapped,
   2056                                      index=self.index).__finalize__(self)

pandas\src\inference.pyx in pandas.lib.map_infer (pandas\lib.c:62578)()

C:\Anaconda3\lib\ast.py in literal_eval(node_or_string)
     82                 return left - right
     83         raise ValueError('malformed node or string: ' + repr(node))
---> 84     return _convert(node_or_string)
     85 
     86 

C:\Anaconda3\lib\ast.py in _convert(node)
     81             else:
     82                 return left - right
---> 83         raise ValueError('malformed node or string: ' + repr(node))
     84     return _convert(node_or_string)
     85 

ValueError: malformed node or string: <_ast.BinOp object at 0x00000253FB0C02B0>
```

I can load in the features, echonest, and genres with no errors.

**Comment by mdeff** [comment] 2018-02-20 22:00
Please see the [Usage section in the README](https://github.com/mdeff/fma/#usage) and do `git checkout rc1`. That's a duplicate of #9.

**Comment by victoreram** [comment] 2018-02-20 23:31
Thank you for the response. I followed that, but now I'm getting a similar error:

```python 
ValueError                                Traceback (most recent call last)
<ipython-input-1-e0b9f0f91162> in <module>()
      1 import utils
----> 2 tracks = utils.load('C:\\Users\\ramir\\OneDrive\\Documents\\GitHub\\fma_metadata\\tracks.csv')
      3 tracks.shape

~\OneDrive\Documents\GitHub\fma\utils.py in load(filepath)
    200                    ('track', 'genres'), ('track', 'genres_all')]
    201         for column in COLUMNS:
--> 202             tracks[column] = tracks[column].map(ast.literal_eval)
    203 
    204         COLUMNS = [('track', 'date_created'), ('track', 'date_recorded'),

C:\Anaconda3\lib\site-packages\pandas\core\series.py in map(self, arg, na_action)
   2052                                      index=self.index).__finalize__(self)
   2053         else:
-> 2054             mapped = map_f(values, arg)
   2055             return self._constructor(mapped,
   2056                                      index=self.index).__finalize__(self)

pandas\src\inference.pyx in pandas.lib.map_infer (pandas\lib.c:62578)()

C:\Anaconda3\lib\ast.py in literal_eval(node_or_string)
     82                 return left - right
     83         raise ValueError('malformed node or string: ' + repr(node))
---> 84     return _convert(node_or_string)
     85 
     86 

C:\Anaconda3\lib\ast.py in _convert(node)
     81             else:
     82                 return left - right
---> 83         raise ValueError('malformed node or string: ' + repr(node))
     84     return _convert(node_or_string)
     85 

ValueError: malformed node or string: nan```

**Comment by stanleyjs** [comment] 2018-12-11 18:53
@mdeff 's `git checkout rc1` fixed this for me.

@mdeff is there a version of `fma_metadata.zip` that can work with `master`?

**Comment by mdeff** [comment] 2020-06-13 03:26
@victoreram I can't reproduce. What's your OS, and versions of python, numpy, and pandas?

**Comment by akshaysmenon93** [comment] 2020-06-16 17:45
I was trying to load tracks.csv on google colab and it gives me the following error : Python - v3.6 , Numpy - v1.18.5 , Pandas - v1.0.4

KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'genres_top'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
pandas/_libs/index.pyx in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc()

5 frames
pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'genres_top'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/multi.py in get_loc(self, key, method)
   2670 
   2671         if keylen == self.nlevels and self.is_unique:
-> 2672             return self._engine.get_loc(key)
   2673 
   2674         # -- partial selection or non-unique index

pandas/_libs/index.pyx in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc()

KeyError: ('track', 'genres_top')

**Closed** 2020-07-20 14:48 UTC
