### ISSUE TITLE
Error while loading tracks.csv

### ISSUE THREAD

**Issue by nathanss** [mdeff/fma#40] opened 2020-06-12 19:40 UTC
Hello,

I am getting an error while trying to load tracks.csv. 

![image](https://user-images.githubusercontent.com/13437655/84540297-5e616080-accb-11ea-98ed-1306974fec80.png)

Any ideas?

**Comment by mdeff** [comment] 2020-06-12 20:08
This behavior was [deprecated in pandas 0.25](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#removal-of-prior-version-deprecations-changes):
> Removed the previously deprecated `ordered` and `categories` keyword arguments in `astype` ([GH17742](https://github.com/pandas-dev/pandas/issues/17742))

Install an older version of pandas (`pandas==0.21.0` was used when developing this code).

**Comment by mdeff** [comment] 2020-06-12 20:15
Actually a duplicate of #34.

**Closed by mdeff** 2020-06-12 20:15 UTC
